[package]
name = "rine-input-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.29"
winit_input_helper = "0.15"
bitflags = "2.4"
rustc-hash = "1.1.0"
